# Generated by Django 2.2.6 on 2019-10-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seats',
            new_name='seat',
        ),
    ]
