# Generated by Django 2.2.6 on 2019-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_auto_20191006_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='noofseats',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
