# Generated by Django 2.2.6 on 2019-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0005_auto_20191007_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='noofseats',
            field=models.IntegerField(null=True),
        ),
    ]
