# Generated by Django 2.2.6 on 2019-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_auto_20191007_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='noofseats',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
