# Generated by Django 2.2.6 on 2019-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0007_auto_20191007_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='noofseats',
            field=models.IntegerField(default=0),
        ),
    ]
