# Generated by Django 2.2.6 on 2019-10-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0010_auto_20191007_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='noofseats',
        ),
    ]
