# Generated by Django 2.2.6 on 2019-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0011_remove_seat_noofseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seats',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
