# Generated by Django 2.2.5 on 2019-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='tname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
