# Generated by Django 2.2.3 on 2019-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviereg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatrename', models.CharField(max_length=30)),
                ('moviename', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('actress', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('stime', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('rowss', models.BigIntegerField()),
                ('colss', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trailer', models.CharField(max_length=255)),
                ('tpic', models.CharField(max_length=255)),
            ],
        ),
    ]
