# Generated by Django 2.1.7 on 2019-03-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='bthdate',
            new_name='birthdate',
        ),
    ]
