# Generated by Django 2.1.7 on 2019-03-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190318_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='updated_at',
        ),
    ]
