# Generated by Django 2.1.7 on 2019-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20190319_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phno',
            field=models.CharField(max_length=15),
        ),
    ]
