# Generated by Django 2.2.3 on 2019-08-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_signup_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
